Forgot to revert User.class which I modified to test if rating feature works fine. Reverting this file back to the original fixes problem not showing user's login name correctly in developer profile & left navigation bar. (Logged In:)
But it causes the following problem when rating a user:
Fatal error: Call to a member function on a non-object in
/usr/lib/sourceforge/www/include/User.class on line 666

Needs to fix rating bug from now on....